part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const CART = _Paths.CART;
  static const CATEGORIES = _Paths.CATEGORIES;
  static const BRANDS = _Paths.BRANDS;
  static const OFFERS = _Paths.OFFERS;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const PAGE_DETAILS = _Paths.PAGE_DETAILS;
  static const ITEM_DETAILS = _Paths.ITEM_DETAILS;
  static const ITEM_FILTERS = _Paths.ITEM_FILTERS;
  static const SEARCH = _Paths.SEARCH;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const REGISTER = _Paths.REGISTER;
  static const CHECK_OUT = _Paths.CHECK_OUT;
  static const ADDADDRESSES = _Paths.ADDADDRESSES;
  static const ORDERS = _Paths.ORDERS;
  static const REVIEWS = _Paths.reviews;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const WISHLIST = _Paths.WISHLIST;
  static const POLICIES = _Paths.POLICIES;
  static const VENDOR_DETAILS = _Paths.VENDOR_DETAILS;
  static const PAGE = _Paths.PAGE;
  static const SIGNIN = _Paths.SIGNIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const BOTTOMSHEET = _Paths.BOTTOMSHEET;
  static const splash = _Paths.splash;
  static const EditProfile = _Paths.EditProfile;
  static const address = _Paths.address;
  static const payments = _Paths.PAYMENTS;
  static const paymentsDetails = _Paths.PAYMENTSDETAILS;
  static const forgotPassword = _Paths.FORGOTPASSWORD;
  static const otp = _Paths.OTP;
  static const resetPassword = _Paths.RESETPASSWORD;
  static const fieldsPasswords = _Paths.fieldsPasswords;
  static const cancelOrder = _Paths.cancelOrder;
  static const vendor = _Paths.VENDOR_DETAILS;
  static const filter = _Paths.filter;
  static const comments = _Paths.Comments;
  static const googleMapView = _Paths.googleMapView;
  static const brands = _Paths.brands;
  static const notification = _Paths.notification;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const notification = '/notification';
  static const brands = '/brands';
  static const googleMapView = '/google-map-view';
  static const Comments = '/comments';
  static const address = '/address';
  static const BRANDS = '/brands';
  static const filter = '/filter';
  static const BOTTOMSHEET = '/bottom-sheet';
  static const SIGNIN = '/sing-in';
  static const SIGNUP = '/sing-out';
  static const CART = '/cart';
  static const CATEGORIES = '/categories';
  static const OFFERS = '/offers';
  static const ACCOUNT = '/account';
  static const PAGE_DETAILS = '/page-details';
  static const ITEM_DETAILS = '/item-details';
  static const ITEM_FILTERS = '/item-filters';
  static const SEARCH = '/search';
  static const SIGN_IN = '/sign-in';
  static const REGISTER = '/register';
  static const PAYMENTS = '/payments';
  static const PAYMENTSDETAILS = '/payment-details';
  static const FORGOTPASSWORD = '/forgot-password';
  static const RESETPASSWORD = '/reset-password';
  static const CHECK_OUT = '/check-out';
  static const ADDADDRESSES = '/add-addresses';
  static const ORDERS = '/orders';
  static const ORDER_DETAILS = '/order-details';
  static const WISHLIST = '/wishlist';
  static const POLICIES = '/policies';
  static const VENDOR_DETAILS = '/vendor-details';
  static const PAGE = '/page';
  static const EditProfile = '/edit-profile';
  static const OTP = '/otp';
  static const fieldsPasswords = '/fields-passwords';
  static const reviews = '/reviews';
  static const cancelOrder = '/cancel-order';
  static const splash = '/splash';
  
}
